#!/bin/bash -eu

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pushd "${ROOT_DIRECTORY}"
  set -e
  docker build --tag=cfinfrastructure/bosh-test ${DOCKERFILE:-"${GOPATH}/src/github.com/cloudfoundry/mega-ci/dockerfiles/bosh-test"}
  docker run -v $PWD:/bosh-test -v ${MEGA_CI:-"${GOPATH}/src/github.com/cloudfoundry/mega-ci"}:/mega-ci cfinfrastructure/bosh-test ${TEST_TASK:-"/mega-ci/scripts/ci/bosh-test/test"}
popd
