#!/bin/bash -eu

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pushd "${ROOT_DIRECTORY}"
  set -e
  docker build --tag=cfinfrastructure/bosh-test ./ci
  docker run -v $PWD:/bosh-test cfinfrastructure/bosh-test /bosh-test/ci/tasks/test/test
popd
